spring:
    application:
        name: order
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: bqitpw
        url: jdbc:mysql://192.168.0.59:3306/springcloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8082

env: dev2