spring:
    application:
        name: order
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: bqitpw
        url: jdbc:mysql://192.168.0.59:3306/springcloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    rabbitmq:
        host: 112.65.124.54
        port: 11056
        username: admin
        password: admin
        virtual-host: /
        listener:
            acknowledge-mode: MANUAL

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8082

env:
    dev5!!!