spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: bqitpw
        url: jdbc:mysql://192.168.0.59:3306/springcloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8

    jpa:
        show-sql: true